config/routes.rb
Rails.application.routes.draw do
  resources :actes
  resources :types_actes
  resources :docteurs
  resources :services
  resources :sejours
  root :to => "patients#index"
  resources :types_donnees_vitales
  resources :donnees_vitales
  resources :contacts
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sejour.rb
class Sejour < ApplicationRecord
	belongs_to :patient
	belongs_to :service
	has_many :actes

	def facture_txt
		contenu = "Facture du #{Date.today.strftime("%Y-%m-%d")}\n"
		contenu += "Patient : #{patient.nom_complet}\n"
		contenu += "Date                           |  Acte                                             |  Réalisé par                     | Coût                   \n"
		contenu += "-------------------------------+---------------------------------------------------+----------------------------------+------------------------\n"
		

		File.open('db/facture.txt',"w+") { |f| f.write(contenu) }
	end

end

app/controllers/sejours_controller.rb
class SejoursController < ApplicationController
  before_action :set_sejour, only: [:show, :edit, :update, :destroy]

  # GET /sejours
  # GET /sejours.json
  def index
    @sejours = Sejour.all
  end

  # GET /sejours/1
  # GET /sejours/1.json
  def show
  end

  # GET /sejours/new
  def new
    @sejour = Sejour.new
  end

  # GET /sejours/1/edit
  def edit
  end

  # POST /sejours
  # POST /sejours.json
  def create
    @sejour = Sejour.new(sejour_params)

    respond_to do |format|
      if @sejour.save
        format.html { redirect_to @sejour, notice: 'Sejour was successfully created.' }
        format.json { render :show, status: :created, location: @sejour }
      else
        format.html { render :new }
        format.json { render json: @sejour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sejours/1
  # PATCH/PUT /sejours/1.json
  def update
    respond_to do |format|
      if @sejour.update(sejour_params)
        format.html { redirect_to @sejour, notice: 'Sejour was successfully updated.' }
        format.json { render :show, status: :ok, location: @sejour }
      else
        format.html { render :edit }
        format.json { render json: @sejour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sejours/1
  # DELETE /sejours/1.json
  def destroy
    @sejour.destroy
    respond_to do |format|
      format.html { redirect_to sejours_url, notice: 'Sejour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sejour
      @sejour = Sejour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sejour_params
      params.require(:sejour).permit(:date_debut, :date_fin, :patient_id, :service_id)
    end
end

app/helpers/sejours_helper.rb
module SejoursHelper
end

app/views/sejours/_form.html.slim
= simple_form_for(@sejour) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date_debut
    = f.input :date_fin
    = f.input :patient_id do
    	= f.select :patient_id, Patient.order(:nom_usage).all.map { |p| [p.nom_complet, p.id, {class: 'form-control'}]}, include_blank: true
    = f.input :service_id do
    	= f.select :service_id, Service.order(:libelle).all.map { |s| [s.libelle, s.id, {class: 'form-control'}] }, include_blank: true


  .form-actions
    = f.button :submit

app/views/sejours/edit.html.slim
h1 Editing sejour

== render 'form'

= link_to 'Show', @sejour
'|
= link_to 'Back', sejours_path

app/views/sejours/index.html.slim
h1 Listing sejours

table
  thead
    tr
      th Date debut
      th Date fin
      th Patient
      th Service
      th
      th
      th

  tbody
    - @sejours.each do |sejour|
      tr
        td = sejour.date_debut.strftime('%d/%m/%Y %H:%M')
        td = sejour.date_fin.strftime('%d/%m/%Y %H:%M')
        td = sejour.try(:patient).try(:nom_complet)
        td = sejour.try(:service).try(:libelle)
        td = link_to 'Show', sejour
        td = link_to 'Edit', edit_sejour_path(sejour)
        td = link_to 'Destroy', sejour, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Sejour', new_sejour_path

app/views/sejours/new.html.slim
h1 New sejour

== render 'form'

= link_to 'Back', sejours_path

app/views/sejours/show.html.slim
p#notice = notice

p
  strong Date debut:
  = @sejour.date_debut
p
  strong Date fin:
  = @sejour.date_fin
p
  strong Patient:
  = @sejour.try(:patient).try(:nom_complet)

p
	strong Service:
	= @sejour.try(:service).try(:libelle)

=@sejour.facture_txt

= link_to 'Edit', edit_sejour_path(@sejour)
'|
= link_to 'Back', sejours_path