config/routes.rb
Rails.application.routes.draw do
  resources :actes
  resources :types_actes
  resources :docteurs
  resources :services
  resources :sejours
  root :to => "patients#index"
  resources :types_donnees_vitales
  resources :donnees_vitales
  resources :contacts
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/docteur.rb
class Docteur < ApplicationRecord
	has_many :services
	has_many :actes
end

app/controllers/docteurs_controller.rb
class DocteursController < ApplicationController
  before_action :set_docteur, only: [:show, :edit, :update, :destroy]

  # GET /docteurs
  # GET /docteurs.json
  def index
    @docteurs = Docteur.all
  end

  # GET /docteurs/1
  # GET /docteurs/1.json
  def show
  end

  # GET /docteurs/new
  def new
    @docteur = Docteur.new
  end

  # GET /docteurs/1/edit
  def edit
  end

  # POST /docteurs
  # POST /docteurs.json
  def create
    # On gère le chargement de l'image ici !!!
    # on récupère l'image dans params[:docteur][:photo]
    # la méthode path permet de savoir où est stocké temporairement l'image
    # la méthode original_filename permet de connaître le nom de l'image
    # 
    # Il y a deux choses à faire :
    # 1 - déplacer l'image dans un endroit où le projet peut facilement accéder aux images /app/assets/images
    # 2 - mettre le nom original du fichier dans le champ photo, c'est pour cela qu'il est de type string
    FileUtils.mv(params[:docteur][:photo].path, "app/assets/images/#{params[:docteur][:photo].original_filename}")
    params[:docteur][:photo] =  params[:docteur][:photo].original_filename
    @docteur = Docteur.new(docteur_params)
    respond_to do |format|
    debugger
      if @docteur.save
        format.html { redirect_to @docteur, notice: 'Docteur was successfully created.' }
        format.json { render :show, status: :created, location: @docteur }
      else
        format.html { render :new }
        format.json { render json: @docteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docteurs/1
  # PATCH/PUT /docteurs/1.json
  def update
    FileUtils.mv(params[:docteur][:photo].path, "app/assets/images/#{params[:docteur][:photo].original_filename}")
    params[:docteur][:photo] =  params[:docteur][:photo].original_filename
    debugger
    respond_to do |format|
      if @docteur.update(docteur_params)
        format.html { redirect_to @docteur, notice: 'Docteur was successfully updated.' }
        format.json { render :show, status: :ok, location: @docteur }
      else
        format.html { render :edit }
        format.json { render json: @docteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docteurs/1
  # DELETE /docteurs/1.json
  def destroy
    @docteur.destroy
    respond_to do |format|
      format.html { redirect_to docteurs_url, notice: 'Docteur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docteur
      @docteur = Docteur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docteur_params
      params.require(:docteur).permit(:nom_usage, :prenom_usage, :nom_naissance, :adeli, :rpps, :photo, service_ids: [])
    end
end

app/helpers/docteurs_helper.rb
module DocteursHelper
end

app/views/docteurs/_form.html.slim
= simple_form_for(@docteur) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nom_usage
    = f.input :prenom_usage
    = f.input :nom_naissance
    = f.input :adeli
    = f.input :rpps
    = f.input :photo, as: :file

  .form-actions
    = f.button :submit

app/views/docteurs/edit.html.slim
h1 Editing docteur

== render 'form'

= link_to 'Show', @docteur
'|
= link_to 'Back', docteurs_path

app/views/docteurs/index.html.slim
h1 Listing docteurs

table
  thead
    tr
      th Nom usage
      th Prenom usage
      th Nom naissance
      th Adeli
      th Rpps
      th Photo
      th
      th
      th

  tbody
    - @docteurs.each do |docteur|
      tr
        td = docteur.nom_usage
        td = docteur.prenom_usage
        td = docteur.nom_naissance
        td = docteur.adeli
        td = docteur.rpps
        td = docteur.photo
        td = link_to 'Show', docteur
        td = link_to 'Edit', edit_docteur_path(docteur)
        td = link_to 'Destroy', docteur, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Docteur', new_docteur_path

app/views/docteurs/new.html.slim
h1 New docteur

== render 'form'

= link_to 'Back', docteurs_path

app/views/docteurs/show.html.slim
p#notice = notice

p
  strong Nom usage:
  = @docteur.nom_usage
p
  strong Prenom usage:
  = @docteur.prenom_usage
p
  strong Nom naissance:
  = @docteur.nom_naissance
p
  strong Adeli:
  = @docteur.adeli
p
  strong Rpps:
  = @docteur.rpps
p
  strong Photo:
  = image_tag @docteur.photo

= link_to 'Edit', edit_docteur_path(@docteur)
'|
= link_to 'Back', docteurs_path