config/routes.rb
Rails.application.routes.draw do
  resources :actes
  resources :types_actes
  resources :docteurs
  resources :services
  resources :sejours
  root :to => "patients#index"
  resources :types_donnees_vitales
  resources :donnees_vitales
  resources :contacts
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/acte.rb
class Acte < ApplicationRecord
	belongs_to :sejour
	belongs_to :patient
	belongs_to :docteur
	belongs_to :type_acte
end

app/controllers/actes_controller.rb
class ActesController < ApplicationController
  before_action :set_acte, only: [:show, :edit, :update, :destroy]

  # GET /actes
  # GET /actes.json
  def index
    @actes = Acte.all
  end

  # GET /actes/1
  # GET /actes/1.json
  def show
  end

  # GET /actes/new
  def new
    @acte = Acte.new
  end

  # GET /actes/1/edit
  def edit
  end

  # POST /actes
  # POST /actes.json
  def create
    @acte = Acte.new(acte_params)

    respond_to do |format|
      if @acte.save
        format.html { redirect_to @acte, notice: 'Acte was successfully created.' }
        format.json { render :show, status: :created, location: @acte }
      else
        format.html { render :new }
        format.json { render json: @acte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actes/1
  # PATCH/PUT /actes/1.json
  def update
    respond_to do |format|
      if @acte.update(acte_params)
        format.html { redirect_to @acte, notice: 'Acte was successfully updated.' }
        format.json { render :show, status: :ok, location: @acte }
      else
        format.html { render :edit }
        format.json { render json: @acte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actes/1
  # DELETE /actes/1.json
  def destroy
    @acte.destroy
    respond_to do |format|
      format.html { redirect_to actes_url, notice: 'Acte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acte
      @acte = Acte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acte_params
      params.require(:acte).permit(:date_heure, :type_acte_id)
    end
end

app/helpers/actes_helper.rb
module ActesHelper
end

app/views/actes/_form.html.slim
= simple_form_for(@acte) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date_heure
    = f.input :type_acte_id

  .form-actions
    = f.button :submit

app/views/actes/edit.html.slim
h1 Editing acte

== render 'form'

= link_to 'Show', @acte
'|
= link_to 'Back', actes_path

app/views/actes/index.html.slim
h1 Listing actes

table
  thead
    tr
      th Date heure
      th Type acte
      th
      th
      th

  tbody
    - @actes.each do |acte|
      tr
        td = acte.date_heure
        td = acte.type_acte_id
        td = link_to 'Show', acte
        td = link_to 'Edit', edit_acte_path(acte)
        td = link_to 'Destroy', acte, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Acte', new_acte_path

app/views/actes/new.html.slim
h1 New acte

== render 'form'

= link_to 'Back', actes_path

app/views/actes/show.html.slim
p#notice = notice

p
  strong Date heure:
  = @acte.date_heure
p
  strong Type acte:
  = @acte.type_acte_id

= link_to 'Edit', edit_acte_path(@acte)
'|
= link_to 'Back', actes_path